#!/usr/bin/env bash
# Turn Material Symbols exports into the symbolic icons Astral embeds.
#
# Google's exports are already close to what GTK wants — a single filled path,
# no strokes — but they need three things doing to them:
#
#   * Renaming. Icon lookup goes current theme -> parents -> hicolor last, and
#     an icon called "search-symbolic" would lose to the system theme's own and
#     never appear. Everything is prefixed "astral-" so it cannot collide. The
#     "-symbolic" suffix is what tells GTK the icon may be recoloured.
#   * A black fill. The exports carry whatever colour the website previewed
#     with, usually a pale grey. GTK overrides it when recolouring, but anything
#     else that renders the file — a thumbnailer, a browser — would show pale
#     grey on white.
#   * A nominal 16px size, which is what these are drawn at in the toolbar. The
#     viewBox is left alone; it defines the coordinate system, not the size.
#
# Sources live in assets/icons-src/ and are left in place; the results go to
# internal/app/icons/, which the app embeds. Most came across from Atlas Notes
# and Atlas Monitor so the three apps share one visual language.
#
# Run from the repository root:  scripts/import-icons.sh
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")/.."
src_dir=assets/icons-src
out_dir=internal/app/icons

# <source name>:<installed name, without the astral-/-symbolic wrapper>
map=(
    arrow_upward:send
    stop:stop
    content_copy:copy
    reset:regenerate
    delete:trash
    edit:edit
    menu:menu
    left_panel_open:panel-left
    chat:chat
    characters:characters
    assistant:designer
    settings:settings
    folder:folder
    add:add
    search:search
    history:history
    info:info
)

mkdir -p "$out_dir"
rm -f "$out_dir"/*.svg

for entry in "${map[@]}"; do
    src="${entry%%:*}"
    name="${entry##*:}"
    in="$src_dir/$src.svg"
    out="$out_dir/astral-$name-symbolic.svg"
    [ -f "$in" ] || { echo "missing source: $in" >&2; exit 1; }

    {
        cat <<'HDR'
<?xml version="1.0" encoding="UTF-8"?>
<!-- Material Symbols (Outlined, weight 400, grade 0, optical size 20),
     Apache License 2.0 — see NOTICE. Filled paths only: GTK recolours a
     symbolic icon by forcing the fill, so a stroke would not follow the
     theme. Generated by scripts/import-icons.sh; edit the source file in
     assets/icons-src rather than this. -->
HDR
        sed -n '/<svg/,$p' "$in" \
            | sed -e 's|height="20px"|height="16"|' \
                  -e 's|width="20px"|width="16"|' \
                  -e 's|fill="#e3e3e3"|fill="#000000"|'
    } > "$out"
done

echo "wrote $(ls -1 "$out_dir"/*.svg | wc -l) icons to $out_dir"
